version: "3.9"

services:
  my_app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "443:443"
      - "80:80"
